### ISSUE TITLE
Clarify and document build process

### ISSUE THREAD

**Issue by pierrepebay** [DARMA-tasking/vt-tv#69]
- Unify variables used during all builds (bindings and C++ standalone) => allow `setup.py` to use all optional variables that can be used in `CMakeLists.txt`
- Document these variables
- Provide an example script to build the standalone C++ executable

**Comment by ppebay** [comment]
I would add that the documentation should also explain:
- [ ] that VTK must be built with `VTK_WRAP_PYTHON` turned `ON` (which is **not** the default CMake setting);
- [ ] whether it is a requirement (which I presume it is -- at least this is how I am doing it in order to build successfully) that the same Python environment (e.g. Conda, etc.) be used to build VTK and vt-tv.

I also surmise that this vt-tv console output:
`selected phase=18446744073709551615`
is incorrect and should be fixed (or documented if this value actually makes sense).
